import Head from 'next/head'
import { Inter } from 'next/font/google'
import Image from 'next/image'
import Init from '../assets/init.svg'
import End from '../assets/end.svg'
import { Container } from '@/styles/pages/app'
import { ContainerHome, InfoHome } from '@/styles/pages/home'
import { Button } from '@/styles/button'
import { useTranslation } from 'react-i18next'



export default function Home() {
  const { t } = useTranslation()

  return (
    <>
      <Head>
        <title>Carlos Uzeda</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>

      <ContainerHome>
      <Image src={Init} alt=''/>
      <span>{t("Hi, my name is")}</span>
      <InfoHome>
      <span>{t("Carlos Uzeda.")}</span>
      <strong>{t("I’m Full Stack Developer")}</strong>
      </InfoHome>
      <span>{t("Welcome to my Web Portfolio!")}</span>
      <Image src={End} alt=''/>
      <Button color='gray'>{t("Learn more")}</Button>
      </ContainerHome>

      </Container>
    
    </>
  )
}
